repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.4.4
  hooks:
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi, jupyter ]
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi, jupyter ]
      args: [ --fix ]
- repo: https://codeberg.org/frnmst/md-toc
  # Release updates (ATOM) https://codeberg.org/frnmst/md-toc/tags.atom
  rev: 9.0.0 # set a GIT tag
  hooks:
  - id: md-toc
    args: ['--in-place', 'github']